from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, cast
from uuid import UUID, uuid4

from packages.agent.orchestrator.models import (
    AgentRoute,
    SessionGoal,
    SessionIntent,
    SessionResponse,
    SessionUserQuery,
    SpecialistResult,
)
from packages.agent.orchestrator.parsing import _iso_now
from packages.knowledge.kpi import (
    KPI_SERVICE_LEVEL,
    KPI_TOTAL_SUPPLY_CHAIN_COST,
    make_stub_kpi_scores,
    weighted_utility,
)
from packages.schemas.recommendation import Candidate, KpiScore, TradeoffExplanation
from packages.tools.guardrail import classify_risk, needs_approval


async def _resolve_weights_with_memory(
    orchestrator: Any,
    goal: SessionGoal,
) -> tuple[dict[str, float], str]:
    from packages.agent.orchestrator.weights import resolve_weights
    from packages.memory import MemoryQuery

    try:
        results = await orchestrator._memory_store.search(
            MemoryQuery(type="user_policy", k=1, min_similarity=0.0, query_text=goal.text)
        )
        if results:
            mem, _score = results[0]
            data = json.loads(mem.content)
            if isinstance(data.get("weights"), dict):
                return data["weights"], "user_policy"
    except Exception:
        pass
    return resolve_weights(goal)


async def _write_decision_memory(
    orchestrator: Any,
    session_id: UUID,
    goal: SessionGoal,
    weights: dict[str, float],
    weight_source: str,
    risk_level: str,
) -> None:
    from packages.memory import Memory

    mem = Memory(
        id=uuid4(),
        scope="global",
        type="user_policy",
        content=json.dumps({
            "goal": goal.text,
            "weights": weights,
            "weight_source": weight_source,
        }),
        metadata={"session_id": str(session_id), "risk_level": risk_level},
        created_at=_iso_now(),
    )
    await orchestrator._memory_store.write(mem)


def _extract_candidates(agent_results: dict[str, SpecialistResult]) -> list[dict[str, Any]]:
    for result in agent_results.values():
        if isinstance(result.output.get("candidates"), list):
            return cast(list[dict[str, Any]], result.output["candidates"])
        tool_results = result.output.get("tool_results")
        if isinstance(tool_results, dict):
            optimizer_output = tool_results.get("optimize_replenishment")
            if (
                isinstance(optimizer_output, dict)
                and isinstance(optimizer_output.get("candidates"), list)
            ):
                return cast(list[dict[str, Any]], optimizer_output["candidates"])
    return []


def _rank_candidates(
    raw_candidates: list[dict[str, Any]],
    weights: dict[str, float],
) -> tuple[Candidate, list[Candidate]]:
    if not raw_candidates:
        raise ValueError(
            "No candidates were generated by the simulation optimizer. "
            "Ensure the simulation_optimizer specialist returned a non-empty 'candidates' list."
        )

    candidates = [
        Candidate(
            id=str(c.get("id", uuid4())),
            action=c.get("action", {"order_qty": c.get("order_qty")}),
            kpi_scores=[KpiScore(**s) for s in c.get("kpi_scores", [])]
            or make_stub_kpi_scores(float(c.get("order_qty", 100.0)), idx),
            constraints_satisfied=c.get("constraints_satisfied", []),
            constraints_violated=c.get("constraints_violated", []),
        )
        for idx, c in enumerate(raw_candidates)
    ]

    utilities = [
        (candidate, weighted_utility(candidate.kpi_scores, weights))
        for candidate in candidates
    ]
    utilities.sort(key=lambda item: item[1], reverse=True)
    primary = utilities[0][0]
    others = [candidate for candidate, _ in utilities[1:]]

    alt_service = max(
        others,
        key=lambda c: next((s.value for s in c.kpi_scores if s.name == KPI_SERVICE_LEVEL), 0.0),
        default=None,
    )
    alt_cost = min(
        others,
        key=lambda c: next(
            (s.value for s in c.kpi_scores if s.name == KPI_TOTAL_SUPPLY_CHAIN_COST),
            float("inf"),
        ),
        default=None,
    )
    alternatives: list[Candidate] = []
    seen: set[str] = set()
    for alt in [alt_service, alt_cost, *others]:
        if alt is not None and alt.id not in seen:
            alternatives.append(alt)
            seen.add(alt.id)
        if len(alternatives) >= 2:
            break
    return primary, alternatives


async def _build_decision_response(
    orchestrator: Any,
    session_id: UUID,
    query: SessionUserQuery,
    intent: SessionIntent,
    route: AgentRoute,
    agent_results: dict[str, SpecialistResult],
) -> SessionResponse:
    goal = SessionGoal(
        text=intent.goal_text or query.text,
        weight_override_json=query.weight_override_json,
    )
    weights, weight_source = await _resolve_weights_with_memory(orchestrator, goal)
    primary, alternatives = _rank_candidates(_extract_candidates(agent_results), weights)

    tradeoff = TradeoffExplanation(
        weight_vector=weights,
        weight_source=weight_source,  # type: ignore[arg-type]
        primary_vs_alternative=[
            {
                "alternative_id": alt.id,
                "primary_advantage": "higher weighted utility",
                "alternative_advantage": f"order_qty={alt.action.get('order_qty')}",
            }
            for alt in alternatives
        ],
    )
    risk_level = classify_risk(primary)
    requires_approval = needs_approval(risk_level)
    await _write_decision_memory(orchestrator, session_id, goal, weights, weight_source, risk_level)

    reply = (
        f"Selected candidate {primary.id} for: {goal.text}\n\n"
        f"Primary action: {primary.action}\n"
        f"Risk level: {risk_level}"
    )
    await orchestrator._push({
        "type": "response_ready",
        "mode": route.mode,
        "risk_level": risk_level,
        "requires_approval": requires_approval,
        "timestamp": _iso_now(),
    })
    if requires_approval:
        await orchestrator._push({
            "type": "approval_requested",
            "approval_id": str(uuid4()),
            "expires_at": (datetime.now(timezone.utc) + timedelta(days=1)).isoformat(),
            "risk_level": risk_level,
            "timestamp": _iso_now(),
        })
    else:
        await orchestrator._push({
            "type": "auto_executed",
            "recommendation_id": str(uuid4()),
            "timestamp": _iso_now(),
        })

    orchestrator._schedule_status_update(
        session_id, "awaiting_approval" if requires_approval else "completed"
    )
    return SessionResponse(
        mode=route.mode,
        reply=reply,
        intent=intent,
        route=route,
        agent_results=agent_results,
        primary=primary,
        alternatives=alternatives,
        tradeoff=tradeoff,
        risk_level=risk_level,
        requires_approval=requires_approval,
    )


async def _synthesize_response(
    orchestrator: Any,
    session_id: UUID,
    query: SessionUserQuery,
    intent: SessionIntent,
    route: AgentRoute,
    agent_results: dict[str, SpecialistResult],
) -> SessionResponse:
    decision_mode = (
        route.mode in ("planned_execution", "dag_execution")
        or "simulation_optimizer" in route.agents
        or any("simulation_optimizer" in key for key in agent_results)
    )
    if decision_mode:
        return await _build_decision_response(
            orchestrator, session_id, query, intent, route, agent_results
        )

    from packages.agent.llm import LLMMessage
    from packages.persistence.agent_steps_repo import make_step

    step_id = await make_step(str(session_id), "synthesis")
    response = await orchestrator._llm_client.complete(
        messages=[
            LLMMessage(
                role="system",
                content=(
                    "Synthesize the agent results into a concise assistant reply. "
                    "Use the same language as the user. Do not invent raw inventory rows."
                ),
            ),
            LLMMessage(
                role="user",
                content=json.dumps(
                    {
                        "query": query.text,
                        "intent": intent.model_dump(),
                        "agent_results": {k: v.output for k, v in agent_results.items()},
                    },
                    default=lambda o: float(o) if isinstance(o, Decimal) else str(o),
                ),
            ),
        ],
        tools=None,
        temperature=0.0,
        max_tokens=1024,
        specialist_role="orchestrator",
        agent_step_id=step_id,
    )
    await orchestrator._push(
        {"type": "response_ready", "mode": route.mode, "timestamp": _iso_now()}
    )
    orchestrator._schedule_status_update(session_id, "completed")
    return SessionResponse(
        mode=route.mode,
        reply=response.text,
        intent=intent,
        route=route,
        agent_results=agent_results,
    )
